validEmail=gopi9310@gmail.com
validPassword=Ashritha1234@1

invalidEmail=test@test.com
invalidPassword=wrong123

searchProduct=Hammer

#firstName=Gopi
#lastName=Velpuri

firstname=Gopi
lastname=Velpuri
dob=2002-01-17
country=India
postalcode=500070
housenumber=12
street=LB Nagar
city=Hyderabad
state=Telangana
phone=9876543210


loginEmail=gopi9310@gmail.com
loginPassword=Ashritha1234@1

registerEmail=gopi9310@gmail.com
registerPassword=Ashritha1234@1

#searchProduct=Hammer