validEmail=customer@practicesoftwaretesting.com
validPassword=welcome01

invalidEmail=test@test.com
invalidPassword=wrong123

searchProduct=Hammer

#firstName=Gopi
#lastName=Velpuri

firstname=Gopi
lastname=Velpuri
dob=2002-01-17
country=India
postalcode=500070
housenumber=12
street=LB Nagar
city=Hyderabad
state=Telangana
phone=9876543210
registeremail=gopi123456@gmail.com
registerpassword=Welcome@123
#searchProduct=Hammer